services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=chienguyen
      - MYSQL_DATABASE=JLOtest 
    volumes:
      - ./mariadb:/var/lib/mysql

  server:
    build: server
    ports:
      - "9000:9000"
    volumes:
      - ./server:/var/www/server
    networks:
      - default
    environment:
      - DB_HOST=db
      - DB_DATABASE=JLOtest
      - DB_USERNAME=root
      - DB_PASSWORD=chienguyen
      - DB_PORT=3306  
    depends_on:
      - db
  nginx:
    build: client
    ports:
      - "80:80"
    networks:
      - default
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./server:/var/www/server
    depends_on:
      - server

networks:
  default:
    driver: bridge